name: Metrics
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics.svg
          user: fumikun
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          repositories_skipped: report
          use_prebuilt_image: yes

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2%

          plugin_lines: yes


          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  

      - name: Metrics 2
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          filename: metrics2.svg
          user: fumikun
          base: ""
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          repositories_skipped: report
          use_prebuilt_image: yes

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200

          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_achievements_ignored: deployer, gister, automator


